name: master

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        pluto: [1.3.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.1.0
        with:
          command: "crictl --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided
// write bassh to loop through all namespaces in kubernetes and add a label  that is environment=prod